#!/bin/bash

interval=0

cpu() {
	cpu_val=$(grep -o "^[^ ]*" /proc/loadavg)

 	printf "  CPU:"
	printf " $cpu_val"
}

sound() {
  volume=$(pamixer --get-volume-human)
  muted=${volume::-1}
  if [ "$muted" == "mute" ]; then
    printf " 婢 VOL:"
  else
    printf " 墳 VOL:"
  fi
  printf " %s" "$volume"
}

pkg_updates() {
	updates=$(checkupdates | wc -l)   # arch , needs pacman contrib

	if [ "$updates" == "0" ]; then
		printf "  Fully Updated"
	else
		printf "  $updates"" updates"
	fi
}

mem() {
	printf "  MEM:"
	printf " $(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)"
}

wlan() {
  printf "  ETH:";
	case "$(cat /sys/class/net/en*/operstate 2>/dev/null)" in
	up) printf " Connected";;
	down) printf " Disconnected";;
	esac
}

internet() {
  ethStatus="down"
  eth=$(cat /sys/class/net/en*/operstate 2> /dev/null)
  eth=($eth)
  for eStat in "${eth[@]}"
  do
    if [ "$eStat" == "up" ]; then
      ethStatus="up"
    fi
  done

  if [ "$ethStatus" == "down" ]; then
    wifi=$(cat /sys/class/net/wl*/operstate 2> /dev/null)
    if [ "$wifi" == "up" ]; then
      wifi=$(iwgetid --raw)
      printf " 直 WIFI:"
      printf " %s" "$wifi"
    else
      printf " 睊 WIFI:"
      printf " Disconnected"
    fi
  else
    printf "  ETH:";
    printf " Connected"
  fi
}

clock() {
	printf " "
  printf " $(date '+%R')"
	# printf " $(date '+%I:%M %p') "
}

day() {
  printf " "
  printf " $(date '+%b %e %Y')"
}

song() {
  playing=$(playerctl -p spotify status)
  if [ "$playing" != "Playing" ]; then
    cur_song="Nothing Playing"
  else
    cur_song=$(playerctl -p spotify metadata --format '{{title}} By: {{artist}}')
  fi
  printf "  Playing:"
  printf " $cur_song"
}

disturb() {
  doNotDisturb=$(dunstctl is-paused)
  if [ $doNotDisturb == "true" ]; then
    printf " "
  else
    printf " "
  fi
}

while true; do

	[ $interval = 0 ] || [ $(($interval % 3600)) = 0 ] && updates=$(pkg_updates)
	interval=$((interval + 1))

	#sleep 1 && xsetroot -name "$updates $(battery) $(brightness) $(cpu) $(mem) $(wlan) $(clock)"
  sleep 1 && xsetroot -name "$(disturb) | $updates | $(song) | $(internet) | $(cpu) | $(mem) | $(sound) | $(clock) | $(day)"
done
